[deploy]
bucket = 'cfn-harvestdam-artifacts'
region = 'us-east-2'
stack_name = 'CrdCicd'

[parameters]
ServiceStack = 'CrdSrvBackendFlask'
ClusterStack = 'CrdCluster'
GitHubBranch = 'prod'
GitHubRepo = 'Nurudeen25/aws-bootcamp-cruddur-2023'
ArtifactBucketName = "codepipeline-harvestdam-artifacts"
BuildSpec = 'backend-flask/buildspec.yml'